@startuml
skin rose

package Modelo {
    abstract class Instrumento {
        -codigo
        -precio
        -stock
        -material
    }

    annotation nota {
        Habran 3 tipos de instrumentos: Cuerda, viento y
        percusión. Cada uno con algunos atributos más,
        como por ejemplo en cuerdas se tendra, tipo de
        cuerda, número de cuerda, etc.
    }
    Instrumento .. nota
}
@enduml